AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS Lambda Function for CloudFormation Custom Resource for AWS Organizations Backup Policy management.
  It should be deployed in the AWS Organizations Management Account

Parameters:
  S3DeploymentBucketName:
    Description: Enter the Amazon S3 bucket name prefix that contains the AWS Lambda deployment package
    Type: AWS::SSM::Parameter::Value<String>
  S3DeploymentPackage:
    Description: Enter the Amazon S3 key name for your AWS Lambda deployment package
    Type: AWS::SSM::Parameter::Value<String>
  BackupOrgPolicyManagerLambdaRoleName:
    Description: The name of the role used by the BackupOrgPolicyManager Lambda function
    Type: String
    Default: BackupOrgPolicyManager
  HomeAccountParameterStore:
    Description: Home Account Number for Backup and Recovery with AWS Backup solution
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  BackupOrgPolicyManager:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BackupOrgPolicyManager
      Description: Lambda function to deploy CloudFormation custom resources
        to AWS Organizations.
      Handler: BackupOrgPolicyManager.lambda_handler
      Code:
        S3Bucket: !Sub "${S3DeploymentBucketName}-${HomeAccountParameterStore}-${AWS::Region}"
        S3Key: !Sub "lambda/${S3DeploymentPackage}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${BackupOrgPolicyManagerLambdaRoleName}"
      Runtime: python3.8
      MemorySize: 256
      Timeout: 300


Outputs:
  LambdaDeploymentBucketName:
    Value: !GetAtt BackupOrgPolicyManager.Arn
    Description: "Lambda function ARN export for use by CloudFormation custom resource"
    Export:
      Name: "aws-backup-backuporgpolicymanager-lambda-arn"



