AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys Backup Policies required to manage backups at an organization level. It should be deployed to the management account.

Parameters:
  pOrgBackupTargetOUs:
    Description: A comma separated list of the AWS Organizations OUs to attach backup policies.
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: "/backup/target/organizational-units"
  pRegions:
    Description: Target regions for backup plans as a comma delimited list
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: "/backup/target/regions"
  pCentralBackupVaultArn:
    Description: The ARN of a centralized AWS Backup Vault that will be the secondary store for all AWS Backups.  The defined organization backup policy plans will "copy_to" this vault.
    Type: AWS::SSM::Parameter::Value<String>
    Default:  "/backup/central-vault-arn"
  pCrossAccountBackupRole:
    Description: This is the IAM role name for the cross-account backup role that carries out the backup activities.
    Type: String
    Default: AWSBackupSolutionRole
  DailyBackupSchedule:
    Description: The CRON job to initiate backup jobs. For example, cron(0 5 ? * * *) for daily, every day at 05:00 UTC.
    Type: String
    Default: cron(0 5 ? * * *)
  MonthlyBackupSchedule:
    Description: The CRON job to initiate backup jobs. For example, cron(0 5 1 * ? *) for monthly, first day of month at midnight UTC.
    Type: String
    Default: cron(0 5 1 * ? *)
  pMemberAccountBackupVault:
    AllowedPattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    ConstraintDescription: The name of the member account Backup vaults. (Name is case sensitive). 
    Type: String
    Default: AWSBackupSolutionVault
  OrgManagementAccount:
    Description: The account number of the AWS Organizations Management account
    Type: AWS::SSM::Parameter::Value<String>
  pBackupTagKey1:
    Type: String 
    Description: The backup tag key to automatically assign resources to a backup plan across the member accounts. 
    Default: 'backup'
  pBackupTagValue1:
    Type: String 
    Description: The backup tag value to automatically assign resources to a backup plan across the member accounts. 
    Default: 'daily'
  pBackupTagKey2:
    Type: String 
    Description: The backup tag key to automatically assign resources to a backup plan across the member accounts. 
    Default: 'backup'
  pBackupTagValue2:
    Type: String 
    Description: The backup tag value to automatically assign resources to a backup plan across the member accounts. 
    Default: 'monthly'
  pTagKey:
    Type: String 
    Description: This is the tag key to assign to resources.
    Default: 'project'
  pTagValue:
    Type: String 
    Description: This is the tag value to assign to resources.
    Default: 'aws-backup'

# TODO:  Update so that backup policy is defined as YAML
# TODO:  Verify that the PolicyTargets works for OUs as well as account ids, member org accounts.

Resources:
  rOrgDailyBackUpPolicy:
    Type: Custom::OrgPolicy
    Properties:
      PolicyName: org-daily-backup-policy
      PolicyType: BACKUP_POLICY
      PolicyTargets: !Ref pOrgBackupTargetOUs
      PolicyRegions: !Ref pRegions
      OrgManagementAccount: !Ref OrgManagementAccount
      PolicyDescription: >-
        BackupPolicy for Daily Backup as per the resource selection criteria
      PolicyContent: !Sub |
        {
            "plans": {
                "OrgBackupPlanDaily": {
                    "rules": {
                        "OrgDailyBackupRule": {
                            "schedule_expression": {
                                "@@assign": "${DailyBackupSchedule}"
                            },
                            "start_backup_window_minutes": {
                                "@@assign": "60"
                            },
                            "complete_backup_window_minutes": {
                                "@@assign": "1200"
                            },
                            "lifecycle": {
                                "delete_after_days": {
                                    "@@assign": "35"
                                }
                            },
                            "target_backup_vault_name": {
                                "@@assign": "${pMemberAccountBackupVault}"
                            },
                            "recovery_point_tags": {
                                "project": {
                                    "tag_key": {
                                        "@@assign": "${pTagKey}"
                                    },
                                    "tag_value": {
                                        "@@assign": "${pTagValue}"
                                    }
                                }
                            },
                            "copy_actions": {
                              "${pCentralBackupVaultArn}": {
                                "target_backup_vault_arn": {
                                  "@@assign": "${pCentralBackupVaultArn}"
                                },
                                "lifecycle": {
                                  "delete_after_days": {
                                    "@@assign": "35"
                                  }
                                }
                            }
                        }
                      }
                    },
                    "backup_plan_tags": {
                        "project": {
                            "tag_key": {
                                "@@assign": "${pTagKey}"
                            },
                            "tag_value": {
                                "@@assign": "${pTagValue}"
                            }
                        }
                    },
                    "selections": {
                        "tags": {
                            "OrgDailyBackupSelection": {
                                "iam_role_arn": {
                                    "@@assign": "arn:aws:iam::$account:role/${pCrossAccountBackupRole}"
                                },
                                "tag_key": {
                                    "@@assign": "${pBackupTagKey1}"
                                },
                                "tag_value": {
                                    "@@assign": [
                                        "${pBackupTagValue1}"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
      ServiceToken:
        Fn::ImportValue: "aws-backup-backuporgpolicymanager-lambda-arn"


  rOrgMonthlyBackUpPolicy:
    Type: Custom::OrgPolicy
    Properties:
      PolicyName: org-monthly-backup-policy
      PolicyType: BACKUP_POLICY
      PolicyTargets: !Ref pOrgBackupTargetOUs
      PolicyRegions: !Ref pRegions
      OrgManagementAccount: !Ref OrgManagementAccount
      PolicyDescription: >-
        BackupPolicy for Monthly Backup as per the resource selection criteria
      PolicyContent: !Sub |
        {
            "plans": {
                "OrgBackupPlanMonthly": {
                    "rules": {
                        "OrgMonthlyBackupRule": {
                            "schedule_expression": {
                                "@@assign": "${MonthlyBackupSchedule}"
                            },
                            "start_backup_window_minutes": {
                                "@@assign": "60"
                            },
                            "complete_backup_window_minutes": {
                                "@@assign": "1200"
                            },
                            "lifecycle": {
                                "delete_after_days": {
                                    "@@assign": "366"
                                }
                            },
                            "target_backup_vault_name": {
                                "@@assign": "${pMemberAccountBackupVault}"
                            },
                            "recovery_point_tags": {
                                "project": {
                                    "tag_key": {
                                        "@@assign": "${pTagKey}"
                                    },
                                    "tag_value": {
                                        "@@assign": "${pTagValue}"
                                    }
                                }
                            },
                            "copy_actions": {
                              "${pCentralBackupVaultArn}": {
                                "target_backup_vault_arn": {
                                  "@@assign": "${pCentralBackupVaultArn}"
                                },
                                "lifecycle": {
                                  "delete_after_days": {"@@assign": "366"}
                                }
                            }
                        }
                      }
                    },
                    "backup_plan_tags": {
                        "project": {
                            "tag_key": {
                                "@@assign": "${pTagKey}"
                            },
                            "tag_value": {
                                "@@assign": "${pTagValue}"
                            }
                        }
                    },
                    "selections": {
                        "tags": {
                            "OrgDailyBackupSelection": {
                                "iam_role_arn": {
                                    "@@assign": "arn:aws:iam::$account:role/${pCrossAccountBackupRole}"
                                },
                                "tag_key": {
                                    "@@assign": "${pBackupTagKey2}"
                                },
                                "tag_value": {
                                    "@@assign": [
                                        "${pBackupTagValue2}"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
      ServiceToken:
        Fn::ImportValue: "aws-backup-backuporgpolicymanager-lambda-arn"

