AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS Organizations Management Account role assumed by BackupOrgPolicyManager Lambda Function to manage organization backup policies.
  It should be deployed in the AWS Organizations management account.
Parameters:
  BackupAndRecoveryHomeAccountId:
    Description: The account number where the Backup and Recovery with AWS Backup solution is deployed
    Type: String

Resources:
  BackupOrgPolicyManagerRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: IAM role should not allow * resource on its permissions policy
          - id: F3
            reason: IAM role should not allow * resource on its permissions policy
    Properties:
      RoleName:  BackupOrgPolicyManagerOrgAdmin
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${BackupAndRecoveryHomeAccountId}:role/BackupOrgPolicyManager"
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: OrgPermissions
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - organizations:CreatePolicy
                  - organizations:DeletePolicy
                  - organizations:AttachPolicy
                  - organizations:DetachPolicy
                  - organizations:ListPolicies
                  - organizations:UpdatePolicy
                  - organizations:DescribePolicy
                  - organizations:ListTargetsForPolicy
                Resource: '*'