AWSTemplateFormatVersion: '2010-09-09'
Description: "Role used by CloudFormation granting permissions to manage AWS resources"
Parameters:
  OrganizationManagementAccountId:
    Description: Enter the AWS Organizations Management Account ID.  This is used to provide CloudFormation with permissions required for AWS Backup policy management.
    Type: String
    
Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationRole
      Description: Role assumed by CloudFormation for deploying resources
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: CloudFormationPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:*
                  - codepipeline:*
                  - ssm:*
                  - secretsmanager:GetSecretValue
                  - lambda:*
                Resource: "*"
              - Sid: AllowOrganizationsRead
                Effect: Allow
                Action:
                  - organizations:Describe*
                  - organizations:List*
                Resource: "*"
              - Sid: AllowBackupPoliciesCreation
                Effect: Allow
                Action:
                  - organizations:CreatePolicy
                Resource: "*"
                Condition:
                  StringEquals:
                    organizations:PolicyType: BACKUP_POLICY
              - Sid: AllowBackupPoliciesModification
                Effect: Allow
                Action:
                  - organizations:DescribePolicy
                  - organizations:UpdatePolicy
                  - organizations:DeletePolicy
                Resource:
                  - !Sub "arn:aws:organizations::${OrganizationManagementAccountId}:policy/*/backup_policy/*"
                Condition:
                  StringEquals:
                    organizations:PolicyType: BACKUP_POLICY
              - Sid: AllowBackupPoliciesAttachmentAndDetachmentToAllAccountsAndOUs
                Effect: Allow
                Action:
                  - organizations:AttachPolicy
                  - organizations:DetachPolicy
                Resource:
                  - !Sub "arn:aws:organizations::${OrganizationManagementAccountId}:root/*"
                  - !Sub "arn:aws:organizations::${OrganizationManagementAccountId}:ou/*"
                  - !Sub "arn:aws:organizations::${OrganizationManagementAccountId}:account/*"
                  - !Sub "arn:aws:organizations::${OrganizationManagementAccountId}:policy/*/backup_policy/*"
                Condition:
                  StringEquals:
                    organizations:PolicyType: BACKUP_POLICY
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - Fn::ImportValue: "aws-backup-s3-bucket-arn"
                  - Fn::Sub:
                      - "${bucketarn}/*"
                      - bucketarn:
                          Fn::ImportValue: "aws-backup-s3-bucket-arn"
              - Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                Resource:
                  Fn::ImportValue: "aws-backup-codepipeline-kms-arn"
                Effect: Allow
