version: 0.2
phases:
  install:
    commands:
      # - env 
      # - apt-get -y update
      - gem install multi_json -v 1.15.0
      - gem install cfn-nag      
  build:
    commands:
      - chmod +x codebuild/ValidateTemplates/run-cfnnag.sh
      - /bin/bash codebuild/ValidateTemplates/run-cfnnag.sh
