Description: "StackSet for Backup and Recovery with AWS Backup Restore Test Validation"
Parameters:
# parameters for stackset
  StackSetName:
    Description: Name of the stackset
    Type: String
    Default: organizations-aws-backup-restore-test-validation
  StackSetS3BucketName:
    Description: Name of S3 bucket where stackset templates are stored.
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/bucket"
  StackSetTemplate:
    Description: Name of stackset template
    Type: String
    Default: "deployment/cloudformation/stacks/aws-backup-restore-test-validation.yaml"
  StackSetDescription:
    Description: Description for StackSet
    Type: String
    Default:  StackSet for Backup and Recovery with AWS Backup Restore Test Validation
  StackSetCentralAccountOUParameterStore:
    Description: Target organization unit ids
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/central-account-ou"
  StackSetCentralBackupAccountIdParameterStore:
    Description: Central backup and restore account id
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/central-account-id"
  StackSetCentralBackupAccountRegionParameterStore:
    Description: Central backup and restore account region
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: "/backup/central-account-region-v2"

  # Parameters for tagging
  CommitId:
    Description: The commit id for the change
    Type: String
  SquadName:
    Description: Squad Name
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - Marketing
      - Engineering
      - R&D
    ConstraintDescription: Must be a valid business unit
    Default:  Engineering
  CostCenter:
    Description: Cost Center for AWS Services
    Type: String
    MinLength: '1'
    MaxLength: '255'
    Default:  '00000'
  env:
    Description: Environment
    Type: String
    AllowedValues:
      - Development
      - QA
      - Production
    ConstraintDescription: Must be a valid environment.
    Default:  Development
  ApplicationOwner:
    Description: Email address of application owner
    Type: String
    Default:  selfserviceservicecatalog@example.com
  Product:
    Description: Product Name
    Type: String
    Default:  Backup


Resources:
  StackSetDeployment:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref StackSetName
#      TemplateBody: String
      TemplateURL: !Sub "https://s3.amazonaws.com/${StackSetS3BucketName}/${StackSetTemplate}"
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      CallAs: DELEGATED_ADMIN
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: !Ref StackSetDescription
      OperationPreferences:
        FailureToleranceCount: 0
#        FailureTolerancePercentage: Integer
        MaxConcurrentCount: 1
#        MaxConcurrentPercentage: Integer
        RegionConcurrencyType: SEQUENTIAL
#        RegionOrder:
#          - String
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        -
          DeploymentTargets:
            Accounts:
              - !Ref StackSetCentralBackupAccountIdParameterStore
            AccountFilterType: INTERSECTION
            OrganizationalUnitIds:
              - !Ref StackSetCentralAccountOUParameterStore
          #          ParameterOverrides:
          #            - Parameter
          Regions:
            - !Ref StackSetCentralBackupAccountRegionParameterStore
      Parameters:
        - ParameterKey: CommitId
          ParameterValue: !Ref CommitId
        - ParameterKey: Product
          ParameterValue: !Ref Product
        - ParameterKey: SquadName
          ParameterValue: !Ref SquadName
        - ParameterKey: CostCenter
          ParameterValue: !Ref CostCenter
        - ParameterKey: env
          ParameterValue: !Ref env
        - ParameterKey: ApplicationOwner
          ParameterValue: !Ref ApplicationOwner
      Tags:
        - Key: product
          Value: !Ref Product
        - Key: CommitId
          Value: !Ref CommitId
        - Key: squad-name
          Value: !Ref SquadName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: env
          Value: !Ref env
        - Key: ApplicationOwner
          Value: !Ref ApplicationOwner

